### ISSUE TITLE
v8

### ISSUE THREAD

**Issue by silviuaavram** [downshift-js/downshift#1454]
List of deliverables:

- [x] Replace open on focus with toggle on input click for useCombobox. https://github.com/downshift-js/downshift/issues/1439
- [ ] Rewrite the status message functionality to contain only getA11yStatusMessage, for all hooks, with cleanup. https://github.com/downshift-js/downshift/issues/1322 https://github.com/downshift-js/downshift/issues/1298 https://github.com/downshift-js/downshift/issues/1244 https://github.com/downshift-js/downshift/issues/1227
- [ ] Create the hooks from https://github.com/downshift-js/downshift/issues/1233.
- [ ] Create the hooks from https://github.com/downshift-js/downshift/issues/1450.
- [ ] Types update for onChange https://github.com/downshift-js/downshift/issues/1225
- [x] isItemDisabled https://github.com/downshift-js/downshift/issues/1176
- [ ] aria-selected only for selected item, not highlighted item, in useCombobox https://github.com/downshift-js/downshift/issues/935.
- [x] React 18 useId changes from https://github.com/downshift-js/downshift/pull/1445
- [x] Update TS and propTypes to reflect latestChanges. https://github.com/downshift-js/downshift/issues/834
- [ ] Update hook props. https://github.com/downshift-js/downshift/issues/1462

**Comment by klarstrup** [comment]
Anything I can do to make v8 happen?

**Comment by silviuaavram** [comment]
Some of the items above have been released in v8.

v9 should cover more of the next ones.

**Comment by klarstrup** [comment]
Nice, very nice.
