### ISSUE TITLE
v9

### ISSUE THREAD

**Issue by silviuaavram** [downshift-js/downshift#1520]
List of deliverables:

- [x] Rewrite the status message functionality to contain only getA11yStatusMessage, for all hooks, with cleanup. https://github.com/downshift-js/downshift/issues/1322 https://github.com/downshift-js/downshift/issues/1298 https://github.com/downshift-js/downshift/issues/1244 https://github.com/downshift-js/downshift/issues/1227
- [ ] Create the hooks from https://github.com/downshift-js/downshift/issues/1233.
- [ ] Create the hooks from https://github.com/downshift-js/downshift/issues/1450.
- [x] Types update for onChange https://github.com/downshift-js/downshift/issues/1225
- [ ] aria-selected only for selected item, not highlighted item, in useCombobox https://github.com/downshift-js/downshift/issues/935.
- [ ] Update hook props. https://github.com/downshift-js/downshift/issues/1462
- [x] Create itemToKey https://github.com/downshift-js/downshift/issues/1495

**Comment by silviuaavram** [comment]
Closing and moving the updated list to v10
