### ISSUE TITLE
v10

### ISSUE THREAD

**Issue by silviuaavram** [downshift-js/downshift#1588]
List of deliverables:

- [ ] Create the hooks from https://github.com/downshift-js/downshift/issues/1233.
- [ ] Create the hooks from https://github.com/downshift-js/downshift/issues/1450.
- [ ] aria-selected only for selected item, not highlighted item, in useCombobox https://github.com/downshift-js/downshift/issues/935.
